### ISSUE TITLE
Windows 8.1 - use Gstreamer 1.x. Where can i get the Jar files to test it?

### ISSUE THREAD

**Issue by shamun** [armouroflight/gstreamer1.x-java#3]
I have used Gstreamer 1.x in Linux But for Windows 8.1 its not working with Visual Studio C++ 2010 properly.

Therefore i have to use Java, but i do not find the Jar files to give a try and test quickly. Can you please kindly make the Jars available for 32-bit and 64-bit so that we can give a quick test drive?

**Comment by armouroflight** [comment]
Sorry I haven't had much time for a while on this.  The native parts are not included in the JARs so you need a GStreamer installation already working.  Given that you should be able to get this working.

The build is maven - it should be easy - mvn compile and mvn jar:jar
